import numpy as np
import pandas as pd
import os
import time, datetime
import boto3
import botocore

# To load the environment variables
from dotenv import load_dotenv
load_dotenv()

# for Database connection
from peewee import MySQLDatabase, Model, TextField
from playhouse.reflection import generate_models, print_model, print_table_sql
from sqlalchemy import create_engine 


def get_source_db_object():
    """
    Function to get the db connection
    :param args. None
    :para returns. db_object
    """
    try:
        engine_source = create_engine('mysql+pymysql://testuser:qwerty123@127.0.0.1:3306/autochek', echo=False)
        
    except Exception as e:
        print(e)
        return None
    return engine_source

def get_destination_db_object():
    """
    Function to get the db connection
    :param args. None
    :para returns. db_object
    """
    try:
        engine_destination  = create_engine('mysql+pymysql://testuser:qwerty123@127.0.0.1:3306/autochek_warehouse', echo=False)
        
    except Exception as e:
        print(e)
        return None
    return engine_destination


def get_db_object():
    """
    Function to get the db connection
    :param args. None
    :para returns. db_object
    """

    try:
        mysql_db = MySQLDatabase(
                os.getenv("DB_DATABASE"),
                user = os.getenv("DB_USERNAME"),
                password = os.getenv("DB_PASSWORD"),
                host = os.getenv("DB_HOST"),
                port = int(os.getenv("DB_PORT"))
            )
        
    except Exception as e:
        print(e)
        return None
    return mysql_db


def get_files_list_for_current_session(input_dir_path, run_id, process_id):
    """
    This function is to get the files list from DB to be downloaded for 
    the current session
    :param args. run_id - an string value, generated by laravel application
    :param args. process_id - an string value, set by airflow
    :param returns. list of string - containing file names for the current session
    """

    # list to store files
    res = []

    # Iterate directory
    for path in os.listdir(input_dir_path):
        # check if current path is a file
        if os.path.isfile(os.path.join(input_dir_path, path)):
            res.append(path)
    
    return res


def put_files_list_for_current_session(dataframe):
    """
    This function is to get the files list from DB to be downloaded for 
    the current session
    :param args. run_id - an string value, generated by laravel application
    :param args. process_id - an string value, set by airflow
    :param returns. list of string - containing file names for the current session
    """

    engine = get_source_db_object()

    # Check column name and select the table name
    table_name = ''
    if list(dataframe)[0] == 'Borrower_Id':
        table_name = 'borrower_table'
    elif list(dataframe)[2] == 'Amount_paid':
        table_name = 'loan_payment'
    elif list(dataframe)[1] == 'loan_id':
        table_name = 'loan_table'
    elif list(dataframe)[1] == 'schedule_id':
        table_name = 'payment_schedule'


    # connect the pandas dataframe with postgresql table 
    query =  dataframe.to_sql(table_name, engine, if_exists='replace', index=False) 
    
    return query

